export const signIn = "/signin"
export const signUp = "/signup"
export const home = "/"
export const projects = "/projects"
export const add = "/add"
export const resetPassword = "/reset"
export const stats = "/stats"